### ISSUE TITLE
Lock screen, inconsistent with logout and switch user interface styles

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-screensaver#13]
锁屏界面，与注销和切换用户界面风格不一致

测试步骤：
1、点击电源-锁屏，界面无毛玻璃效果
2、点击电源-注销/切换用户，界面有毛玻璃效果，与锁屏界面风格不一致

**Comment by xiaodongliu-nudt** [comment]
cannot reappear this issue on my computer.

**Comment by liumin0322** [comment]
20200328版本测试通过。
