### ISSUE TITLE
创建多个用户后，登录界面默认居中的用户不是管理员用户

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-screensaver#17]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200302-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、系统中创建多个用户
2、查看开机后登录界面显示的用户排列

预期结果：默认用户为管理员用户

实际结果：默认用户为最新创建的用户

**Comment by liuyuanpeng176** [comment]
刚刚提交的github，默认用户为上次登录的用户。

**Comment by liuyuanpeng176** [comment]
这是登录(ukui-greeter)的bug

**Comment by xiaodongliu-nudt** [comment]
20200320解决
