### ISSUE TITLE
登录界面，点击触发焦点后，焦点不会消失

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-screensaver#18]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200302-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、在切换用户登录界面
2、点击“中文”语言选项，再点击“UK”桌面环境选项

预期结果：点击其他选项后，点击焦点消失

实际结果：两个按钮均出现点击触发焦点

**Comment by liuyuanpeng176** [comment]
新提交的已修复

**Comment by liuyuanpeng176** [comment]
这是登录(ukui-greeter)的bug

**Comment by xiaodongliu-nudt** [comment]
20200320修复
