### ISSUE TITLE
分辨率为800*600时，登录界面的登录框显示不完全

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-screensaver#20]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200309-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、打开控制面板，设置分辨率为800*600
2、锁屏切换至登录界面

预期结果：登录界面分辨率自适应

实际结果：登录界面显示导致输入框看不到

**Comment by liumin0322** [comment]
20200321版本测试未通过

**Comment by liuyuanpeng176** [comment]
最新的提交已修改

**Comment by liumin0322** [comment]
Tested pass in the 20200410 version
