### ISSUE TITLE
双屏显示，登录界面花屏

### ISSUE THREAD

**Issue by Liang-zy** [ukui/ukui-screensaver#27]
版本：20.04LTS
iso：ubuntukylin-ukui3.0-20200313-amd64.iso
测试环境：联想兆芯E  CF4620Z笔记本
测试环境：联想启天M415-N000台式机
测试步骤：
1.双屏显示
2.注销，重启，切换用户

预期结果： 登录界面无异常
实际结果：登录界面，鼠标在两个屏幕之间滑动，出现花屏现象；注销或重启到登录界面也会花屏

**Comment by liuyuanpeng176** [comment]
和bug#11重复
