### ISSUE TITLE
锁屏界面卡住，鼠标可以移动，点击无反应。键盘不能输入 

### ISSUE THREAD

**Issue by Liang-zy** [ukui/ukui-screensaver#32]
版本：20.04LTS
iso：ubuntukylin-ukui3.0-20200320-amd64.iso
测试环境：联想兆芯E  CF4620Z笔记本
测试环境：联想启天M415-N000台式机
测试步骤：
1.锁定屏幕界面
2.按esc 键

预期结果：进入屏幕保护程序
实际结果：概率性出现，按esc键，锁屏界面卡住，鼠标可以移动，点击无反应。键盘不能输入

**Comment by liuyuanpeng176** [comment]
没有复现出来，然后锁屏已经去掉了响应esc显示屏保的功能，这个bug应该就不存在了。

**Comment by ikeyhzj** [comment]
20200521 version test pass
