### ISSUE TITLE
【屏保】在高分屏上，屏保显示异常

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-screensaver#45]
在华为笔记本，分辨率为3000*2000，屏保显示效果如下图预览图
![2020-04-07 15-46-27屏幕截图](https://user-images.githubusercontent.com/48200161/78643519-f6675600-78e6-11ea-8ed7-c8984b6ffcf1.png)

**Comment by liuyuanpeng176** [comment]
因为qt设置了缩放的环境变量，会放大窗口，使用qt的函数是能够得到正确的大小的，但由于锁屏使用的是x的函数获取的大小，然后得到了放大后的大小，又经由qt放大，所以窗口放大了四倍。

**Comment by liumin0322** [comment]
test passed in the 20200418
