### ISSUE TITLE
【高分屏】锁屏界面的背景图片被拉伸

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-screensaver#46]
![2020-04-07 17-04-01屏幕截图](https://user-images.githubusercontent.com/48200161/78651056-5dd6d300-78f2-11ea-837f-ecaee3a5366d.png)

**Comment by liuyuanpeng176** [comment]
锁屏背景大小是从x拿的屏幕大小，大小是高分屏的大小，所以显示不正确，已修改为qt的函数。

**Comment by liumin0322** [comment]
test passed in the 20200418
