### ISSUE TITLE
Screen saver interface, mouse click [Exit (Esc)] will not exit the screen saver

### ISSUE THREAD

**Issue by Liang-zy** [ukui/ukui-screensaver#49]
Version: 20.04LTS
Iso: ubuntukylin-ukui3.0-20200410-amd64.iso
Test environment: Lenovo Qitian M415-N000 desktop
Test steps:
1. Wait for the lock screen to enter the screen saver interface
2. Click 【Exit / Esc】
Expected result: Exit screen saver
Actual result: No response after clicking

**Comment by liuyuanpeng176** [comment]
类似与windows，屏保在按下任意键后都可以退出，所以不是很有必要显示这个按钮，所以去除了这个按钮。

**Comment by liumin0322** [comment]
Tested pass in the 20200418 version
