### ISSUE TITLE
从开始菜单里调用切换用户后不能用小键盘的数字键

### ISSUE THREAD

**Issue by moshengrenzenme** [ukui/ukui-screensaver#6]
在开始菜单里调用切换用户后小键盘数字键上不能使用的，NumLock是亮着的，只有再按两次NumLock才行

**Comment by liuyuanpeng176** [comment]
0314版本没有复现

**Comment by moshengrenzenme** [comment]
@liuyuanpeng176 并不是不能复现，而是在后来的版本经被修复了，但是你们没有关闭这个issue
