### ISSUE TITLE
ukui-screensaver hijacks firefox

### ISSUE THREAD

**Issue by nexryai** [ukui/ukui-screensaver#98]
If you install this package, it will force the Firefox top page to be set to 123.sogou.com. Even worse, even if you restore the settings, it will still be set to 123.sogou.com every time you reboot. It is recommended to remove such browser hijackers for the sake of users.

Installation repository: https://download.opensuse.org/repositories/X11:/UKUI:/Factory/openSUSE_Tumbleweed/
Environment: openSUSE Tumbleweed

**Comment by handsome-feng** [comment]
Is there a ubuntukylin.cfg in your /usr/lib/firefox/browser/defaults/preferences/ directory?

**Comment by nexryai** [comment]
Yes, I found it.
It turns out that this file was installed by `ubuntukylin-default-settings`.
It's not a problem with ukui-screensaver itself. Thanks for the quick response and sorry for the inconvenience.

**Comment by handsome-feng** [comment]
@nexryai Hi, I didn't find ubuntukylin-default-settings in your installation repository, how did you install it? I don't think it should be ported to any other distributions than Ubuntu Kylin.

**Comment by nexryai** [comment]
Some dependencies were missing from the openSUSE repository, so I retrieved some dependencies from the openEluer repository. (Both are rpm repositories, so they are compatible.)
I think it was installed with them.
